use_frameworks!

target 'JKImagePicker_Example' do
  pod 'JKImagePicker', :path => '../'
  pod 'SMInstagramPhotoPicker'

  target 'JKImagePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
